AllCops:
  TargetRubyVersion: 2.2

Metrics/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/AndOr:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Style/RedundantSelf:
  Enabled: false

Style/SymbolProc:
  Enabled: false
